#!/bin/bash
# generate_report.sh - Generate comprehensive sync status report
# Usage: ./generate_report.sh [--output FILE]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

OUTPUT_FILE=""
if [[ "$1" == "--output" && -n "$2" ]]; then
    OUTPUT_FILE="$2"
fi

# Function to output (to file or stdout)
output() {
    if [[ -n "$OUTPUT_FILE" ]]; then
        echo "$1" >> "$OUTPUT_FILE"
    else
        echo "$1"
    fi
}

# Clear output file if specified
if [[ -n "$OUTPUT_FILE" ]]; then
    > "$OUTPUT_FILE"
fi

output "# AILANG Documentation Sync Report"
output ""
output "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
output ""

# Version info
ACTUAL_VERSION=$(cd "$PROJECT_ROOT" && git describe --tags --abbrev=0 2>/dev/null || echo "unknown")
VERSION_FILE="$PROJECT_ROOT/docs/src/constants/version.js"
WEBSITE_VERSION=$(grep "STABLE_RELEASE" "$VERSION_FILE" 2>/dev/null | grep -o "v[0-9]\+\.[0-9]\+\.[0-9]\+" || echo "unknown")
LATEST_PROMPT=$(ls -1 "$PROJECT_ROOT/prompts"/v*.md 2>/dev/null | sort -V | tail -1 | xargs basename 2>/dev/null | sed 's/.md//' || echo "unknown")

output "## Version Status"
output ""
output "| Source | Version |"
output "|--------|---------|"
output "| Git tag | $ACTUAL_VERSION |"
output "| Website constant | $WEBSITE_VERSION |"
output "| Latest prompt | $LATEST_PROMPT |"
output ""

if [[ "$WEBSITE_VERSION" != "$ACTUAL_VERSION" ]]; then
    output "**ACTION REQUIRED**: Update \`docs/src/constants/version.js\`"
    output ""
fi

# Design docs status
output "## Design Docs Status"
output ""

PLANNED_COUNT=$(find "$PROJECT_ROOT/design_docs/planned" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
IMPLEMENTED_COUNT=$(find "$PROJECT_ROOT/design_docs/implemented" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')

output "| Category | Count |"
output "|----------|-------|"
output "| Planned | $PLANNED_COUNT |"
output "| Implemented | $IMPLEMENTED_COUNT |"
output ""

# Planned features by version
output "### Planned by Version"
output ""
for dir in "$PROJECT_ROOT/design_docs/planned"/v0_*; do
    if [[ -d "$dir" ]]; then
        version=$(basename "$dir" | sed 's/_/./g')
        count=$(find "$dir" -name "*.md" | wc -l | tr -d ' ')
        output "- **$version**: $count documents"
    fi
done
output ""

# Website structure
output "## Website Structure"
output ""

DOCS_DIR="$PROJECT_ROOT/docs/docs"
output "### Current Sections"
output ""
for dir in "$DOCS_DIR"/*/; do
    if [[ -d "$dir" ]]; then
        section=$(basename "$dir")
        count=$(find "$dir" -name "*.md" -o -name "*.mdx" 2>/dev/null | wc -l | tr -d ' ')
        output "- **$section**: $count pages"
    fi
done
output ""

# Landing pages status
output "## Landing Pages Status"
output ""
output "| Page | Last Modified | Issues |"
output "|------|---------------|--------|"

for page in intro.mdx vision.mdx why-ailang.mdx; do
    filepath="$DOCS_DIR/$page"
    if [[ -f "$filepath" ]]; then
        modified=$(stat -f "%Sm" -t "%Y-%m-%d" "$filepath" 2>/dev/null || stat -c "%y" "$filepath" 2>/dev/null | cut -d' ' -f1 || echo "unknown")

        # Check for issues
        issues=""
        if grep -q "Coming in v0.4" "$filepath" 2>/dev/null; then
            issues="Stale v0.4 reference"
        fi
        if grep -q "v0.4.4" "$filepath" 2>/dev/null; then
            issues="${issues:+$issues, }Outdated prompt ref"
        fi

        output "| $page | $modified | ${issues:-OK} |"
    fi
done
output ""

# Theoretical pages that need status
output "## Theoretical/Future Pages"
output ""
output "These pages document future features and need status banners:"
output ""

ARCH_DIR="$DOCS_DIR/architecture"
if [[ -d "$ARCH_DIR" ]]; then
    for file in "$ARCH_DIR"/*.mdx "$ARCH_DIR"/*.md; do
        if [[ -f "$file" ]]; then
            basename=$(basename "$file")

            # Check if it has a status banner
            if grep -q "PLANNED" "$file" 2>/dev/null; then
                output "- [OK] $basename has status banner"
            else
                output "- [NEEDS BANNER] $basename"
            fi
        fi
    done
fi
output ""

# Summary
output "## Summary"
output ""
output "### Immediate Actions"
output ""
if [[ "$WEBSITE_VERSION" != "$ACTUAL_VERSION" ]]; then
    output "1. [ ] Update version.js to $ACTUAL_VERSION"
fi
output "2. [ ] Add PLANNED banners to architecture pages"
output "3. [ ] Update 'Coming in v0.4' sections"
output "4. [ ] Verify all examples work"
output ""

output "---"
output "*Report generated by docs-sync skill*"

if [[ -n "$OUTPUT_FILE" ]]; then
    echo "Report written to: $OUTPUT_FILE"
fi
