#!/usr/bin/env bash
# Helper script to remind Claude to use WebSearch for model information
# This is a placeholder - actual search is done by Claude using WebSearch tool

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Model Information Search"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  This script is a placeholder for Claude's WebSearch tool."
echo ""
echo "When invoked by Claude, the workflow is:"
echo ""
echo "1. Use WebSearch tool to find:"
echo "   - Official API documentation"
echo "   - Exact API model names"
echo "   - Pricing information"
echo "   - Release announcements"
echo ""
echo "2. Look for:"
echo "   • API model name (e.g., 'gpt-5.1', not 'GPT-5.1')"
echo "   • Provider documentation (OpenAI Platform, Anthropic, Google AI)"
echo "   • Pricing per 1M tokens (convert to per 1K)"
echo "   • Context limits"
echo "   • Special features (caching, reasoning, etc.)"
echo ""
echo "3. Search queries to try:"
echo "   • '[Model Name] API documentation pricing'"
echo "   • '[Model Name] API model name'"
echo "   • '[Provider] pricing page 2025'"
echo ""
echo "4. Verify information from:"
echo "   ✓ platform.openai.com (OpenAI)"
echo "   ✓ docs.anthropic.com (Anthropic)"
echo "   ✓ ai.google.dev or cloud.google.com (Google)"
echo "   ✗ Avoid third-party aggregators (may be outdated)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "For Claude: Use the WebSearch tool now to find this information."
