package mission

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// apply is the ONLY verb that changes what runs. install renders to *.staged and is
// safe at any moment; apply promotes those files and reloads launchd, which kills a
// running iteration. Keeping them separate is not style — the driver re-sources its
// env file on every fire, so a render written in place would apply itself on the next
// interval with nobody reloading anything.

// Bounded waits. launchd's bootout is asynchronous and bootstrap can block on a busy
// domain, so every step carries a deadline — the same standing rule the driver holds
// itself to (`_mc_bounded`). Worst case is bounded at 35s and apply never retries on
// its own: a wedged domain is reported, not worked around.
const (
	bootoutDeadline   = 10 * time.Second
	bootstrapDeadline = 10 * time.Second
	verifyDeadline    = 15 * time.Second
	pollInterval      = 250 * time.Millisecond
)

var (
	// ErrBusy means an iteration is running. Reloading would kill it mid-flight.
	ErrBusy = errors.New("mission is mid-iteration")
	// ErrNeedsAdopt is HD-3(c): the installed artifacts were not generated by this
	// tool, so applying would discard whatever a human put there.
	ErrNeedsAdopt = errors.New("first adoption needs --adopt")
	// ErrNotStaged means install has not been run.
	ErrNotStaged = errors.New("nothing staged")
	// ErrBootoutTimeout and friends are typed so a caller can tell a wedged domain
	// from a rejected command.
	ErrBootoutTimeout   = errors.New("launchctl bootout did not settle within the deadline")
	ErrBootstrapTimeout = errors.New("launchctl bootstrap did not settle within the deadline")
	ErrVerifyTimeout    = errors.New("job did not reach a running state within the deadline")
)

// generatedMarker appears in every plist this package renders. Its ABSENCE means the
// installed plist is hand-written and applying would silently discard it — which is
// what HD-3(c) exists to prevent, and what would otherwise have thrown away v1's ~40
// lines of ratified cadence rationale.
const generatedMarker = "GENERATED by `ailang mission install"

// LaunchCtl is the launchd surface apply needs. Injected so the bounded-wait logic is
// testable without booting out a live mission — the alternative is logic that can only
// be exercised by breaking the fleet it protects.
type LaunchCtl interface {
	Bootout(label string) error
	Bootstrap(plistPath string) error
	// Print returns `launchctl print`'s output, or an error if the job is unknown.
	Print(label string) (string, error)
}

// realLaunchCtl drives the actual launchctl in the caller's GUI domain.
type realLaunchCtl struct{ uid string }

// NewLaunchCtl targets gui/<uid>, which is where the mission jobs live.
func NewLaunchCtl() LaunchCtl { return &realLaunchCtl{uid: strconv.Itoa(os.Getuid())} }

func (l *realLaunchCtl) domain() string { return "gui/" + l.uid }

func (l *realLaunchCtl) Bootout(label string) error {
	// A non-zero exit here usually means "not loaded", which is the state we want.
	_ = exec.Command("launchctl", "bootout", l.domain()+"/"+label).Run() //nolint:gosec // label from the registry
	return nil
}

func (l *realLaunchCtl) Bootstrap(plistPath string) error {
	out, err := exec.Command("launchctl", "bootstrap", l.domain(), plistPath).CombinedOutput() //nolint:gosec // path from the registry
	if err != nil {
		return fmt.Errorf("launchctl bootstrap: %w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

func (l *realLaunchCtl) Print(label string) (string, error) {
	out, err := exec.Command("launchctl", "print", l.domain()+"/"+label).CombinedOutput() //nolint:gosec // label from the registry
	if err != nil {
		return string(out), fmt.Errorf("launchctl print: %w", err)
	}
	return string(out), nil
}

// ApplyOpts controls one apply.
type ApplyOpts struct {
	// Adopt acknowledges HD-3(c) for a mission whose installed artifacts were not
	// generated by this tool.
	Adopt bool
	// Force overrides the busy check (HD-4(b)) — the escape hatch for a wedged loop.
	Force bool
	// SkipReload promotes the files without touching launchd. Useful when the next
	// scheduled fire will pick the change up anyway and killing the current
	// iteration is not worth it.
	SkipReload bool
	// BackupDir receives copies of the pre-apply artifacts.
	BackupDir string
}

// ApplyResult reports what happened, so a caller can print it rather than guess.
type ApplyResult struct {
	Promoted []string
	Backups  []string
	Reloaded bool
	Notes    []string
}

// missionBusy reports whether the mission holds a live pidfile.
func missionBusy(p Paths, m *Mission) (bool, int) {
	// The v1 mission's pidfile keeps its historical name, like its launchd label.
	base := "mission-" + m.launchdSuffix() + ".pid"
	pidPath := p.Home + "/.ailang/state/" + base
	data, err := os.ReadFile(pidPath) //nolint:gosec // derived from the registry
	if err != nil {
		return false, 0
	}
	pid, err := strconv.Atoi(strings.TrimSpace(strings.Split(string(data), "\n")[0]))
	if err != nil || pid <= 0 {
		return false, 0
	}
	// Signal 0 tests for existence without delivering anything.
	if err := syscallKill0(pid); err != nil {
		return false, pid
	}
	return true, pid
}

// Apply promotes the staged artifacts and (unless skipped) reloads the job.
func Apply(m *Mission, p Paths, lc LaunchCtl, opts ApplyOpts) (*ApplyResult, error) {
	res := &ApplyResult{}
	envTarget, plistTarget := p.EnvPath(m.Name), p.PlistPath(m)
	envStaged, plistStaged := envTarget+StagedSuffix, plistTarget+StagedSuffix

	for _, s := range []string{envStaged, plistStaged} {
		if _, err := os.Stat(s); err != nil {
			return nil, fmt.Errorf("%w: %s is absent — run `ailang mission install %s` first", ErrNotStaged, s, m.Name)
		}
	}

	// HD-4(b): never RELOAD a mission mid-iteration — bootout kills the running one.
	//
	// The check is scoped to the reload, not to the whole operation, and that
	// distinction is the point of --no-reload: promotion alone is survivable,
	// because the running iteration already sourced its env at start and the new
	// plist is inert until launchd reloads it. Gating promotion on busy-ness made
	// --no-reload useless for the one case it exists to serve — found by using it
	// on a live mid-iteration v1.
	if busy, pid := missionBusy(p, m); busy && !opts.Force && !opts.SkipReload {
		return nil, fmt.Errorf("%w (pid %d) — wait for it to finish, or pass --force to kill it", ErrBusy, pid)
	} else if busy && !opts.SkipReload {
		res.Notes = append(res.Notes, fmt.Sprintf("--force: proceeding while pid %d is mid-iteration; that iteration will be killed", pid))
	} else if busy {
		res.Notes = append(res.Notes, fmt.Sprintf("pid %d is mid-iteration but --no-reload was given: it keeps running, and the new plist takes effect at the next reload", pid))
	}

	// HD-3(c): a plist we did not generate may hold anything, so the first adoption
	// of each mission is one deliberate acknowledgement rather than a silent clobber.
	installed, err := os.ReadFile(plistTarget) //nolint:gosec // derived from the registry
	switch {
	case os.IsNotExist(err):
		// Nothing to discard; a new mission needs no acknowledgement.
	case err != nil:
		return nil, fmt.Errorf("failed to read %s: %w", plistTarget, err)
	case !strings.Contains(string(installed), generatedMarker) && !opts.Adopt:
		return nil, fmt.Errorf("%w: %s was not generated by this tool and applying would "+
			"discard it (v1's plist, for one, carries ~40 lines of ratified cadence rationale). "+
			"Diff it, move anything worth keeping into missions/%s.toml, then re-run with --adopt",
			ErrNeedsAdopt, plistTarget, m.Name)
	}

	// Back up what is about to be replaced. Cheap, and the alternative is asking a
	// human to reconstruct a plist from memory.
	if opts.BackupDir != "" {
		if err := os.MkdirAll(opts.BackupDir, 0o750); err != nil {
			return nil, fmt.Errorf("failed to create backup dir: %w", err)
		}
		stamp := time.Now().UTC().Format("20060102T150405Z")
		for _, src := range []string{envTarget, plistTarget} {
			body, rerr := os.ReadFile(src) //nolint:gosec // derived from the registry
			if rerr != nil {
				continue // nothing there to back up
			}
			dst := filepath.Join(opts.BackupDir, baseName(src)+"."+stamp+".bak")
			if werr := writeAtomic(dst, body, 0o600); werr != nil {
				return nil, werr
			}
			res.Backups = append(res.Backups, dst)
		}
	}

	// Promote. Rename is atomic per file; doing both back to back is the closest
	// this can get to all-or-nothing without a transactional filesystem, and the
	// order matters: the plist is inert until launchd reloads, whereas the env is
	// live on the next fire, so the env goes LAST.
	for _, pair := range [][2]string{{plistStaged, plistTarget}, {envStaged, envTarget}} {
		if err := os.Rename(pair[0], pair[1]); err != nil {
			return nil, fmt.Errorf("failed to promote %s -> %s: %w", pair[0], pair[1], err)
		}
		res.Promoted = append(res.Promoted, pair[1])
	}

	if opts.SkipReload {
		res.Notes = append(res.Notes, "reload skipped: the env is live on the next fire; the plist needs a reload to take effect")
		return res, nil
	}
	if err := reload(lc, m, plistTarget); err != nil {
		return res, err
	}
	res.Reloaded = true
	return res, nil
}

// reload boots the job out and back in, bounded at every step.
func reload(lc LaunchCtl, m *Mission, plistPath string) error {
	label := m.Label()

	_ = lc.Bootout(label)
	// bootout is asynchronous: poll until the job is genuinely gone.
	if err := until(bootoutDeadline, func() bool {
		_, err := lc.Print(label)
		return err != nil
	}); err != nil {
		return fmt.Errorf("%w (%s, %s)", ErrBootoutTimeout, label, bootoutDeadline)
	}

	done := make(chan error, 1)
	go func() { done <- lc.Bootstrap(plistPath) }()
	select {
	case err := <-done:
		if err != nil {
			return fmt.Errorf("bootstrap %s: %w (staged copies retained for a re-apply)", label, err)
		}
	case <-time.After(bootstrapDeadline):
		return fmt.Errorf("%w (%s, %s)", ErrBootstrapTimeout, label, bootstrapDeadline)
	}

	if err := until(verifyDeadline, func() bool {
		out, err := lc.Print(label)
		return err == nil && (strings.Contains(out, "state = running") || strings.Contains(out, "state = waiting"))
	}); err != nil {
		out, _ := lc.Print(label)
		return fmt.Errorf("%w (%s, %s): %s", ErrVerifyTimeout, label, verifyDeadline, firstLines(out, 5))
	}
	return nil
}

// until polls cond until it is true or the deadline expires.
func until(deadline time.Duration, cond func() bool) error {
	end := time.Now().Add(deadline)
	for {
		if cond() {
			return nil
		}
		if time.Now().After(end) {
			return errors.New("deadline expired")
		}
		time.Sleep(pollInterval)
	}
}

// baseName must split on the HOST's separator, not on "/" alone. A hand-rolled
// LastIndex(p, "/") returns the WHOLE path for a windows path like
// C:\Users\...\mission-alpha.env, and joining that under the backup dir produces
// ...\bak\C:\Users\... — a second drive letter mid-path, which windows refuses
// with "The filename, directory name, or volume label syntax is incorrect".
// filepath.Base is identical to the old code for "/"-separated paths.
func baseName(p string) string {
	return filepath.Base(p)
}

func firstLines(s string, n int) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, " | ")
}
