// gen-env-docs renders docs/docs/reference/env-vars.md from config.Registry,
// so the environment-variable reference is generated from the same table the
// getters read their names and defaults from and cannot drift. Run via:
// make docs-env
package main

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/sunholo-data/ailang/internal/config"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gen-env-docs <output.md>")
		os.Exit(1)
	}
	out := render(config.Registry, config.Areas)
	if err := os.WriteFile(os.Args[1], out, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-env-docs: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("gen-env-docs: wrote %s (%d variables in %d areas)\n", os.Args[1], len(config.Registry), len(config.Areas))
}

// render groups the registry by area, in Areas order, sorted by name within
// an area, and emits one Docusaurus page.
func render(vars []config.Var, areas []string) []byte {
	byArea := map[string][]config.Var{}
	for _, v := range vars {
		byArea[v.Where] = append(byArea[v.Where], v)
	}
	var b bytes.Buffer
	b.WriteString(`---
sidebar_position: 12
title: Environment Variables
description: Every environment variable AILANG reads, with its default and what it does. Generated from internal/config — do not edit by hand.
---

# Environment Variables

`)
	fmt.Fprintf(&b, "Generated by `make docs-env` from `internal/config` (%d variables). Do not edit; edit the `Var` beside the getter and regenerate.\n\n", len(vars))
	b.WriteString(`**Precedence, everywhere:** a command-line flag beats the environment, the environment beats
` + "`~/.ailang/config.yaml`" + `, and the file beats the default. A getter in ` + "`internal/config`" + ` returns what the
environment says (or the default); the command that owns a flag applies it above, and the
package that owns a config-file section reads it below.

An empty **Default** means the variable is unset by default: the feature is off, or the value
comes from the fallback the description names. The ` + "`DEBUG_*`" + ` compiler knobs are documented in
[Debugging](../guides/debugging.md), not here.

`)
	for _, area := range areas {
		list := byArea[area]
		if len(list) == 0 {
			continue
		}
		sort.Slice(list, func(i, j int) bool { return list[i].Name < list[j].Name })
		fmt.Fprintf(&b, "## %s\n\n| Variable | Default | What it does |\n|---|---|---|\n", area)
		for _, v := range list {
			def := "—"
			if v.Default != "" {
				def = "`" + v.Default + "`"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", v.Name, def, cell(v.Doc))
		}
		b.WriteString("\n")
	}
	return b.Bytes()
}

// cell makes a doc line safe inside a Markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	// Angle brackets read as JSX in MDX; spell them out.
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}
