// Command gen-anchor generates the frozen ELO anchor panel (anchor_vN.json)
// from a REAL banked corpus. The anchor is generated, never authored: this
// tool exists because a hand-written anchor with invented values silently
// corrupts every rating fitted against it (M-EVAL-ROLLING-ELO, rejection of
// task-08f450a0, 2026-08-27).
//
// Usage:
//
//	go run ./tools/gen-anchor --out internal/eval_harness/anchor_v1.json \
//	    eval_results/baselines/v0.32.0 [more result dirs...]
//
// Selection rule (design doc M-EVAL-ROLLING-ELO, D1):
//   - standard-mode rows only (agent-mode difficulty is a different scale)
//   - blended across languages (same trial construction as tools/eval-elo's
//     standard fit — the store consumers read)
//   - discriminating band only: Band(rating) != "Trivial"
//   - no smoke-tier benchmarks (≈2 fleet rows each → difficulty unidentifiable;
//     the pool-composition artifact class)
//   - no grader-artifact benchmarks (difficulty reflects the grader, not the task)
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/sunholo-data/ailang/internal/eval_analysis"
	"github.com/sunholo-data/ailang/internal/eval_harness"
)

// graderArtifact mirrors internal/eval_analysis/ratings_export.go
// graderArtifactFlags (unexported there). Keep in sync; these benchmarks'
// difficulty measures the grader, not the task, so they cannot pin a scale.
var graderArtifact = map[string]bool{
	"contract_sorted_merge":  true,
	"decision_block_capture": true,
}

// harnessArtifact: benchmarks whose standard-mode difficulty is a KNOWN harness
// defect, not task difficulty — input_files never reaches standard-mode prompts
// (design_docs/planned/v0_33_1/m-eval-standard-mode-input-files-gap.md), so the
// whole fleet fails them for reasons unrelated to capability. Anchoring them
// would hand every model a rating windfall the day the harness bug is fixed.
// When that fix lands, regenerate as anchor_v2 (re-anchor protocol, design D1).
var harnessArtifact = map[string]bool{
	"docx_reimplement":     true,
	"markdown_reimplement": true,
}

func main() {
	out := flag.String("out", "internal/eval_harness/anchor_v1.json", "output path")
	benchDir := flag.String("bench-dir", "benchmarks", "benchmark spec dir (for tier lookup)")
	flag.Parse()
	dirs := flag.Args()
	if len(dirs) == 0 {
		fmt.Fprintln(os.Stderr, "usage: gen-anchor [--out FILE] <results_dir> [results_dir...]")
		os.Exit(2)
	}

	results, err := eval_analysis.LoadResultsFromDirs(dirs...)
	if err != nil {
		fmt.Fprintf(os.Stderr, "load: %v\n", err)
		os.Exit(1)
	}

	var trials []eval_harness.Trial
	for _, r := range results {
		if r.EvalMode == "agent" {
			continue
		}
		trials = append(trials, eval_harness.Trial{
			Model: r.Model,
			Bench: r.ID,
			Pass:  r.CompileOk && r.RuntimeOk && r.StdoutOk,
		})
	}
	if len(trials) == 0 {
		fmt.Fprintln(os.Stderr, "no standard-mode trials in corpus — refusing to emit an empty anchor")
		os.Exit(1)
	}

	_, benchRatings := eval_harness.FitFromTrials(trials)

	tier := func(id string) string {
		spec, err := eval_harness.LoadSpec(filepath.Join(*benchDir, id+".yml"))
		if err != nil {
			return "core" // LoadSpec's own default; absent spec = retired bench, still filterable by band
		}
		return spec.Tier
	}

	panel := map[string]float64{}
	excluded := map[string]int{"trivial_band": 0, "smoke_tier": 0, "grader_artifact": 0, "harness_artifact": 0}
	for bench, rating := range benchRatings {
		switch {
		case eval_harness.Band(rating) == "Trivial":
			excluded["trivial_band"]++
		case tier(bench) == "smoke":
			excluded["smoke_tier"]++
		case graderArtifact[bench]:
			excluded["grader_artifact"]++
		case harnessArtifact[bench]:
			excluded["harness_artifact"]++
		default:
			panel[bench] = float64(int(rating*10)) / 10
		}
	}
	if len(panel) < 10 {
		fmt.Fprintf(os.Stderr, "panel has only %d benchmarks — corpus too thin to pin a scale, refusing\n", len(panel))
		os.Exit(1)
	}

	doc := struct {
		Version     string             `json:"version"`
		Description string             `json:"description"`
		Corpus      []string           `json:"corpus"`
		CorpusRows  int                `json:"corpus_rows"`
		CorpusDate  string             `json:"corpus_date"`
		FitParams   string             `json:"fit_params"`
		Excluded    map[string]int     `json:"excluded_counts"`
		Benchmarks  map[string]float64 `json:"benchmarks"`
	}{
		Version:     "anchor_v1",
		Description: "Frozen ELO anchor panel: benchmark difficulties fitted from the corpus below and held fixed in placement fits (M-EVAL-ROLLING-ELO D1). GENERATED by tools/gen-anchor — do not edit by hand.",
		Corpus:      dirs,
		CorpusRows:  len(trials),
		CorpusDate:  time.Now().UTC().Format("2006-01-02"),
		FitParams:   "FitFromTrials: epochs=400, k=4+28*exp(-e/80), divisor 400, seed 1500",
		Excluded:    excluded,
		Benchmarks:  panel,
	}

	// Deterministic key order for reviewable diffs.
	buf, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "marshal: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, append(buf, '\n'), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	keys := make([]string, 0, len(panel))
	for k := range panel {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	fmt.Printf("anchor_v1: %d benchmarks (excluded: %v) from %d trials -> %s\n", len(panel), excluded, len(trials), *out)
	for _, k := range keys {
		fmt.Printf("  %-32s %7.1f\n", k, panel[k])
	}
}
