#!/bin/bash
# Generate version constants from source of truth files
# Used by CI and local builds to keep documentation in sync

set -e

# Change to repo root
cd "$(dirname "$0")/../.."

# Extract git version
GIT_VERSION=$(git describe --tags 2>/dev/null || echo "v0.0.0-unknown")

# Extract active prompt version from prompts/versions.json
ACTIVE_PROMPT=$(jq -r '.active' prompts/versions.json 2>/dev/null || echo "v0.4.2")

# Extract latest stable release from git tags (most recent vX.Y.Z tag)
# NO FALLBACK - fail loudly if tags aren't available (requires fetch-depth: 0 in CI)
STABLE_RELEASE=$(git tag -l 'v*.*.*' --sort=-v:refname | head -1)
if [ -z "$STABLE_RELEASE" ]; then
  echo "❌ ERROR: No git tags found. Ensure 'fetch-depth: 0' is set in CI checkout."
  echo "   Run 'git fetch --tags' or check your git configuration."
  exit 1
fi

# Extract dev version from CHANGELOG.md (first unreleased version)
DEV_VERSION=$(grep -m1 "^## \[Unreleased - v" CHANGELOG.md | sed 's/.*\[Unreleased - \(v[0-9.]*\)\].*/\1/' || echo "v0.4.4")

# Extract test coverage from make target
COVERAGE=$(make test-coverage-badge 2>/dev/null | grep -o "[0-9.]*%" | head -1 || echo "37.2%")

# Generate JavaScript constants file
cat > docs/src/constants/version.js << EOF
/**
 * Auto-generated version constants
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-version-constants.sh
 *
 * Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
 * Source of truth:
 *   - GIT_VERSION: git describe --tags
 *   - ACTIVE_PROMPT: prompts/versions.json
 *   - STABLE_RELEASE: git tag -l 'v*.*.*' (latest)
 *   - DEV_VERSION: CHANGELOG.md (unreleased)
 *   - COVERAGE: make test-coverage-badge
 */

/** Current git version (e.g., v0.4.3-12-gc0be3540) */
export const GIT_VERSION = '${GIT_VERSION}';

/** Active teaching prompt version (e.g., v0.4.2) */
export const ACTIVE_PROMPT = '${ACTIVE_PROMPT}';

/** Latest stable release (e.g., v0.4.3) */
export const STABLE_RELEASE = '${STABLE_RELEASE}';

/** Next development version (e.g., v0.4.4) */
export const DEV_VERSION = '${DEV_VERSION}';

/** Test coverage percentage (e.g., 37.2%) */
export const COVERAGE = '${COVERAGE}';

/** Short version for display (e.g., v0.4.3) */
export const AILANG_VERSION = '${STABLE_RELEASE}';

// Legacy aliases for backward compatibility
export const CURRENT_VERSION = STABLE_RELEASE;
export const PROMPT_VERSION = ACTIVE_PROMPT;
EOF

echo "✅ Generated docs/src/constants/version.js"
echo "   GIT_VERSION = ${GIT_VERSION}"
echo "   ACTIVE_PROMPT = ${ACTIVE_PROMPT}"
echo "   STABLE_RELEASE = ${STABLE_RELEASE}"
echo "   DEV_VERSION = ${DEV_VERSION}"
echo "   COVERAGE = ${COVERAGE}"
