package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/sunholo-data/ailang/internal/pkg"
)

// semverCoreRe matches the vMAJOR.MINOR.PATCH release prefix of a version string,
// e.g. "v0.25.0-197-g46d5405d2-dirty" -> "v0.25.0". The leading `v` is optional.
var semverCoreRe = regexp.MustCompile(`^v?[0-9]+\.[0-9]+\.[0-9]+`)

// releaseCore extracts the release core (vMAJOR.MINOR.PATCH) from a version string,
// dropping any git-describe suffix (-N-ghash, -dirty). Returns "" when the string has
// no semver core (e.g. "dev", "unknown"). Callers skip the skew check on "" rather than
// compare against a non-release build — a No-Silent-Fallback: we only warn on a real,
// decidable release mismatch, never on a guess about a dev binary.
func releaseCore(v string) string {
	m := semverCoreRe.FindString(strings.TrimSpace(v))
	if m == "" {
		return ""
	}
	if !strings.HasPrefix(m, "v") {
		m = "v" + m
	}
	return m
}

// findLockFile walks up from start (a directory) looking for the nearest ailang.lock,
// returning its path or "" if none is found before the filesystem root.
func findLockFile(start string) string {
	dir := start
	for {
		candidate := filepath.Join(dir, pkg.LockFileName)
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// skewWarning returns a VER001 warning message when the ailang.lock nearest to target
// was generated by a DIFFERENT release than binVersion, else "". target may be a file or
// directory; the search walks up to the filesystem root. The decision is pure (no I/O to
// stderr) so it is unit-testable; warnToolchainSkew wraps it for the CLI.
//
// Motivation (docparse feedback): a std/net breaking change (httpRequest Err: string ->
// NetError) surfaced only as "cannot unify type constructors: string vs NetError" with no
// hint it was toolchain skew — a repo whose lock was cut by an older ailang, checked with a
// newer binary. The type error alone doesn't point at the cause; this note does.
func skewWarning(target, binVersion string) string {
	abs, err := filepath.Abs(target)
	if err != nil {
		return ""
	}
	// If target is a file, search from its directory.
	if info, statErr := os.Stat(abs); statErr == nil && !info.IsDir() {
		abs = filepath.Dir(abs)
	}

	lockPath := findLockFile(abs)
	if lockPath == "" {
		return ""
	}
	lf, err := pkg.LoadLockFileFromPath(lockPath)
	if err != nil || lf.AILANGVersion == "" {
		return ""
	}

	lockCore := releaseCore(lf.AILANGVersion)
	binCore := releaseCore(binVersion)
	// Only warn on a decidable mismatch: both sides must carry a real release core.
	if lockCore == "" || binCore == "" || lockCore == binCore {
		return ""
	}

	// Show the lock path relative to cwd when it lives at/under it, else absolute.
	shown := lockPath
	if cwd, cwdErr := os.Getwd(); cwdErr == nil {
		if rel, relErr := filepath.Rel(cwd, lockPath); relErr == nil && !strings.HasPrefix(rel, "..") {
			shown = rel
		}
	}

	return fmt.Sprintf(
		"WARNING VER001 (toolchain-skew): %s was generated by ailang %s, but this binary is %s.\n"+
			"  A type error such as \"cannot unify type constructors: string vs NetError\" may be stdlib version skew, not your code.\n"+
			"  Fix: regenerate the lock with `ailang lock` (accept the newer stdlib), or install the %s toolchain to match.\n",
		shown, lockCore, binCore, lockCore)
}

// warnToolchainSkew prints a VER001 toolchain-skew warning to stderr when target's
// ailang.lock was cut by a different release than the running binary. It is a hint only —
// it never fails the check. Callers gate on non-quiet/non-JSON output.
func warnToolchainSkew(target string) {
	if msg := skewWarning(target, Version); msg != "" {
		fmt.Fprint(os.Stderr, msg)
	}
}
