package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// CLI reference generator (M-V1-SIMPLIFY-S5 M6, Phase 3 item 6).
//
// docs/docs/reference/cli.md is rendered from the dispatch table, because the
// table is the only place a command name is written down and a hand-written
// page would drift from it exactly as help.go's 505 hand-written lines had
// drifted before M1 (15 commands the switch accepted never appeared in them).
//
// Why the renderer lives HERE and not in tools/ alongside gen-env-docs: the
// table is `package main` in cmd/ailang, so no other package can read it.
// gen-env-docs reads internal/config, which is importable; there is no
// equivalent for the CLI table short of exporting it, and exporting a table
// only so a generator can read it puts a second consumer on a structure whose
// whole value is having one.
//
// The gate is cli_reference_test.go, which renders fresh from the table and
// byte-compares against the CHECKED-IN page. That direction matters: a gate
// pointed at the generated artifact measures the build, not the intent —
// which is how the prompt-truth fix in this same sprint passed on a clean
// checkout and went red after the next `make lint`.
//
// Nothing in the binary calls renderCLIReference. That is deliberate: M6's
// acceptance bar is that the CLI surface does not move, and adding a route —
// even a hidden one — would move it. The test is the entry point, and
// `make docs-cli` runs the test with -update.

// cliReferencePath is where the generated page is checked in, relative to the
// repository root.
const cliReferencePath = "docs/docs/reference/cli.md"

// cliReferenceHeader is the static prose. It is static because it answers
// questions the table does not carry — which flag spelling is canonical, how
// help is reached — and because the generator, not the page, is where a
// correction has to land to survive the next regeneration.
//
// Every command line quoted below was run against the binary before it was
// written down (the rule in CLAUDE.md: verify a syntax claim with the tool,
// never write it from memory).
const cliReferenceHeader = `---
sidebar_position: 13
title: CLI Reference
description: Every ailang command and group, generated from the dispatch table in cmd/ailang/commands.go — do not edit by hand.
---

# CLI Reference

Generated by ` + "`make docs-cli`" + ` from the dispatch table in ` + "`cmd/ailang/commands.go`" + `.
Do not edit this page; edit the ` + "`Command`" + ` row and regenerate. ` + "`make check-cli-docs`" + ` fails
if the page and the table disagree.

## Finding a command

` + "```bash" + `
ailang --help              # the visible top level, one screen
ailang <group> --help      # everything filed in a group (dev, ops, eval)
ailang help <command>      # one command's own help
ailang <command> --help    # the same thing, spelled the other way
` + "```" + `

` + "`--help`" + ` exits 0 at every level and runs nothing. An unknown command prints one line
and a suggestion on stderr and exits 1 — it does not dump the command list into your pipe.

## Output conventions

| Question | Flag | Notes |
|---|---|---|
| Machine-readable output | ` + "`--json`" + ` | The one output-format flag. ` + "`ailang test --json`" + `, not ` + "`--format json`" + `. |
| Which model | ` + "`--model`" + ` | ` + "`ailang eval-suite --models`" + ` is accepted as an alias of the same target. |
| Where output goes | ` + "`--output`" + ` | Six of the eight sites. ` + "`ailang compile --out`" + ` and ` + "`ailang eval-publish --output-dir`" + ` are not converged yet. |
| Gate a mutation | ` + "`--dry-run`" + ` | Audited at all 14 sites: the default **acts**, and ` + "`--dry-run`" + ` is the opt-out everywhere. No command inverts it. |

Superseded spellings keep working — ` + "`ailang test --format json`" + ` still means ` + "`--json`" + ` —
because the fleet and fifteen frozen teaching prompts call them. They are not the spelling to
learn. Two commands keep a ` + "`--format`" + ` of their own for a reason that is not output format:
` + "`ailang check --format agent`" + ` selects a third rendering (and ` + "`ailang ai-check`" + ` is
` + "`ailang check --verify --format agent`" + `), and ` + "`ailang exec --stream-json`" + ` is an NDJSON
event stream, which is not what ` + "`--json`" + ` means there.

Two commands parse ` + "`--format`" + ` by hand rather than registering it, so they do **not** accept
` + "`--json`" + ` and were invisible to the flag audit that converged the rest:
` + "`ailang eval-report --format=markdown|html|docusaurus|json|csv`" + ` and
` + "`ailang doctor managed_agents --format=json`" + `. Both need the ` + "`=`" + ` form. Converging them is a
follow-up, not a documentation problem.

## Groups are a drawer, not a rename

` + "`ailang messages list`" + ` and ` + "`ailang ops messages list`" + ` are the same route. A group exists
so ` + "`ailang --help`" + ` fits on one screen; **every grouped command keeps its own top-level
spelling**, and no script, skill or launchd driver has to change.

`

// cliReferenceFooter closes the page with the facts a reader needs that are
// not a command row: the one command whose behaviour depends on something
// outside its own flags, and which commands are contractually quiet at
// startup.
//
// The documentation-search note is the content of docs/docs/guides/cli.md,
// an 11-line page that was in no sidebar and that M6 retired: these four facts
// are not in `ailang docs search --help`, and the env var is in
// reference/env-vars.md, so the page had exactly this much to say.
const cliReferenceFooter = `
## Documentation search

` + "`ailang docs search \"query\"`" + ` searches the local ` + "`design_docs/`" + ` or ` + "`docs/`" + ` corpus first, and
falls back to GitHub code search when run outside a source checkout. The fallback requires
authentication — ` + "`GITHUB_TOKEN`" + ` or ` + "`gh auth login`" + `; unauthenticated search is not attempted.
` + "`--path <dir>`" + ` forces a local corpus and ` + "`--no-github`" + ` (or ` + "`AILANG_NO_GITHUB_SEARCH`" + `) disables the
fallback. GitHub results are cached per query for one hour under
` + "`~/.ailang/cache/docsearch/github/`" + `; a cache entry holds results and metadata only, never tokens.

## Startup contract

Language commands — the ones you run to work *with* AILANG rather than to operate the fleet —
open no observatory database and run no git probe at startup. This is a contract with a test
behind it (` + "`cmd/ailang/commands_probe_test.go`" + ` counts the probes), not a presentation choice,
and it holds for a command's group spelling too: ` + "`ailang dev builtins`" + ` is as quiet as
` + "`ailang builtins`" + `.

`

// cliReferenceRow is one table row, already rendered to strings.
type cliReferenceRow struct {
	spelling  string
	alsoKnown string
	summary   string
}

// renderCLIReference builds the whole page from allCommands.
func renderCLIReference() []byte {
	var b bytes.Buffer
	b.WriteString(cliReferenceHeader)

	b.WriteString("## Commands\n\n")
	b.WriteString("The visible top level: what `ailang --help` lists.\n\n")
	writeCLITable(&b, "Command", "Also accepted", topLevelRows())

	for _, g := range dispatchGroups {
		fmt.Fprintf(&b, "\n## `ailang %s` — %s\n\n", g, groupSummaries[g])
		fmt.Fprintf(&b, "Reachable as `ailang %s <command>` and, unchanged, as `ailang <command>`.\n\n", g)
		writeCLITable(&b, "Command", "Top-level spelling", groupRows(g))
	}

	if rows := compatibilityRows(); len(rows) > 0 {
		b.WriteString("\n## Compatibility spellings\n\n")
		b.WriteString("Routes the binary still accepts but no longer lists. They exist so an existing\n")
		b.WriteString("caller keeps working; new code should use the canonical spelling.\n\n")
		writeCLITable(&b, "Route", "Use instead", rows)
	}

	b.WriteString(cliReferenceFooter)
	writeLanguageCommandLine(&b)
	return b.Bytes()
}

// topLevelRows is the visible top level, in the order `ailang --help` prints.
func topLevelRows() []cliReferenceRow {
	var rows []cliReferenceRow
	for _, c := range visibleTopLevel() {
		rows = append(rows, cliReferenceRow{
			spelling:  "`ailang " + c.Name + "`",
			alsoKnown: aliasCell(c),
			summary:   c.Summary,
		})
	}
	return rows
}

// groupRows lists one group's visible members, each with the top-level
// spelling D1 guarantees still works, plus any extra subcommand the group
// answers to that has no row of its own (`ailang eval run`).
func groupRows(group string) []cliReferenceRow {
	var rows []cliReferenceRow
	for _, c := range groupMembers(group) {
		if c.Hidden {
			continue
		}
		rows = append(rows, cliReferenceRow{
			spelling:  "`ailang " + group + " " + groupSubName(group, c.Name) + "`",
			alsoKnown: "`ailang " + c.Name + "`" + aliasSuffix(c),
			summary:   c.Summary,
		})
	}
	for _, extra := range groupExtraRows[group] {
		rows = append(rows, cliReferenceRow{
			spelling:  "`ailang " + group + " " + extra[0] + "`",
			alsoKnown: "`ailang " + group + "`",
			summary:   extra[1],
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].spelling < rows[j].spelling })
	return rows
}

// compatibilityRows are the hidden rows that are still routes: the folded
// legacy namespaces and the bare `pkg` verbs. The group entry points (`dev`,
// `ops`) are hidden too but are not compatibility spellings — they are the
// drawers themselves, and the page documents them as headings.
func compatibilityRows() []cliReferenceRow {
	var rows []cliReferenceRow
	for i := range allCommands {
		c := &allCommands[i]
		if !c.Hidden || isGroupName(c.Name) {
			continue
		}
		rows = append(rows, cliReferenceRow{
			spelling:  "`ailang " + c.Name + "`" + aliasSuffix(c),
			alsoKnown: compatibilityReplacement(c),
			summary:   c.Summary,
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].spelling < rows[j].spelling })
	return rows
}

// compatibilityReplacement names the canonical spelling for a hidden route.
//
// It is derived, never listed: the folded namespaces come from
// foldedNamespaces() and the bare verbs from pkgLegacyTopLevel, so the page
// cannot name a replacement the binary does not route. Deriving it from Group
// alone would be wrong for exactly the four rows that matter — `trace` is
// filed under `ops`, but its canonical spelling after M3 is `ailang chains
// trace`, not `ailang ops trace`.
func compatibilityReplacement(c *Command) string {
	for _, ns := range foldedNamespaces() {
		if ns.Legacy == c.Name {
			return "`ailang chains " + ns.Sub + "`"
		}
	}
	if c.Group == groupPkg {
		return "`ailang pkg " + pkgVerbFor(c.Name) + "`"
	}
	// Everything else hidden is an internal entry point with no public
	// spelling to point at (`internal-dump-iface`, which
	// internal/pkg/iface_subprocess.go execs).
	return "—"
}

// pkgVerbFor inverts pkgLegacyTopLevel: the verb whose bare top-level spelling
// is name. Deriving it keeps the page from carrying a second copy of the map.
func pkgVerbFor(name string) string {
	for verb, top := range pkgLegacyTopLevel {
		if top == name {
			return verb
		}
	}
	return name
}

// aliasCell renders a command's aliases for the top-level table.
func aliasCell(c *Command) string {
	if len(c.Aliases) == 0 {
		return "—"
	}
	var out []string
	for _, a := range c.Aliases {
		out = append(out, "`ailang "+a+"`")
	}
	return strings.Join(out, ", ")
}

// aliasSuffix appends ", `ailang <alias>`" for a row rendered inline.
func aliasSuffix(c *Command) string {
	if len(c.Aliases) == 0 {
		return ""
	}
	var out []string
	for _, a := range c.Aliases {
		out = append(out, "`ailang "+a+"`")
	}
	return ", " + strings.Join(out, ", ")
}

// writeLanguageCommandLine names the Language commands, from the table.
func writeLanguageCommandLine(b *bytes.Buffer) {
	var names []string
	for i := range allCommands {
		c := &allCommands[i]
		if c.Language && !c.Hidden {
			names = append(names, "`"+c.Name+"`")
		}
	}
	sort.Strings(names)
	fmt.Fprintf(b, "The language commands are %s.\n", strings.Join(names, ", "))
}

// writeCLITable renders one markdown table. A summary may contain a pipe
// (none does today), so escape it rather than produce a broken table. The
// page is MDX, where a bare `<name>` is a JSX tag: the `bin` summary's
// "uninstall <name>" broke the docs build for three deploys (da1174b4c..)
// before the renderer learned to escape it.
func writeCLITable(b *bytes.Buffer, head1, head2 string, rows []cliReferenceRow) {
	fmt.Fprintf(b, "| %s | %s | What it does |\n|---|---|---|\n", head1, head2)
	for _, r := range rows {
		fmt.Fprintf(b, "| %s | %s | %s |\n", escapePipes(r.spelling), escapePipes(r.alsoKnown), escapeSummary(r.summary))
	}
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

// escapeSummary makes prose safe inside an MDX table cell: a pipe ends the
// cell, and an angle bracket outside a code span opens JSX. The spelling
// columns are code spans, where MDX leaves `<...>` alone, so only the
// summary gets this.
func escapeSummary(s string) string {
	s = escapePipes(s)
	s = strings.ReplaceAll(s, "<", `\<`)
	s = strings.ReplaceAll(s, ">", `\>`)
	return s
}
