package main

import (
	"fmt"
	"io"
	"os"
)

// platformCommands are the commands that operate the fleet rather than the
// language: the message plane, the coordinator, the observatory, the registry
// and the local services. They keep the startup probes (observatory health +
// stale binary) that language commands must not run — none of them sets
// Language, which is what makes platformStartup probe for them.
//
// S5 M2 filed them under the hidden `ops` and `dev` groups. Filing is NOT
// renaming: every row below keeps its top-level route, so `ailang messages
// list` (593 fleet references), `ailang coordinator start` (332) and `ailang
// chains tree` (216) are untouched, and each also answers to `ailang ops
// <name>`. Only the help listing changed.
//
// Two rows are visible at the top level rather than grouped: `pkg` and `serve`,
// both named in the Phase 3 item-2 visible list. `serve` was spelled `server`
// until this milestone; the two swapped roles, so both still resolve.
//
// The eight bare registry verbs that used to live here — `add`, `lock`,
// `tree`, `install`, `search`, `publish`, `unpublish`, `pkg-docs` — are gone
// from this table on purpose. They are now generated by pkgLegacyCommands()
// from the `pkg` verb table, so the verb and its bare spelling share one
// definition instead of two that can drift.
func platformCommands() []Command {
	return []Command{
		{
			Name:    "doctor",
			Group:   groupDev,
			Summary: "Environment diagnostics (builtins, memory, managed_agents, ...)",
			Run:     noArgs(runDoctor),
		},
		{
			Name:    "messages",
			Group:   groupOps,
			Aliases: []string{"msg"},
			Summary: "Agent message plane: list, send, read, ack",
			Run:     noArgs(messagesCommand),
		},
		{
			Name:    "cache",
			Group:   groupDev,
			Aliases: []string{"brain"},
			Summary: "Project brain / semantic cache operations",
			Run:     noArgs(cacheCommand),
		},
		{
			Name:    "micro-rag",
			Group:   groupDev,
			Aliases: []string{"microrag", "urag"},
			Summary: "Micro-RAG index and retrieval operations",
			Run:     noArgs(microragCommand),
		},
		{
			Name:    "agent-prompt",
			Group:   groupDev,
			Summary: "Display the AILANG agent prompt",
			Run:     noArgs(runAgentPrompt),
		},
		{
			Name:    "mcp",
			Group:   groupOps,
			Summary: "Model Context Protocol server operations",
			Run:     noArgs(runMCPCommand),
		},
		{
			Name:    "daemon",
			Group:   groupOps,
			Summary: "Local ailang daemon: run, install, uninstall, status",
			Run:     runDaemonCommand,
		},
		{
			// `serve` is the visible spelling (Phase 3 item 2 lists it among
			// the 17); `server`, which was the canonical name until S5 M2,
			// keeps working as the alias -- 63 observatory-era references
			// spell it that way (D1).
			Name:    "serve",
			Aliases: []string{"server"},
			Summary: "Start the Observatory dashboard server (default port 1957)",
			Run:     serverCommand,
		},
		{
			Name:    "serve-api",
			Group:   groupOps,
			Summary: "Serve AILANG exports as REST endpoints",
			Run:     serveAPICommand,
		},
		{
			Name:    "access-control",
			Group:   groupOps,
			Summary: "Access control management",
			Run:     accessControlCommand,
		},
		{
			Name:    "editor",
			Group:   groupDev,
			Summary: "Install editor syntax highlighting (vscode, vim, neovim)",
			Run:     noArgs(editorCommand),
		},
		{
			Name:    "pi",
			Group:   groupDev,
			Summary: "Manage pi extensions (install, uninstall, status)",
			Run:     noArgs(piCommand),
		},
		{
			Name:    "axioms",
			Group:   groupDev,
			Summary: "Design axiom compliance scorecard",
			Run:     noArgs(axiomsCommand),
		},
		// The three folded rows below, and `eval-chains` in commands_eval.go,
		// are M-V1-SIMPLIFY-S5 M3's aliases. Hidden, because the canonical
		// spelling is now `ailang chains <namespace> ...` and help should stop
		// advertising a name that goes away after one release — but still
		// present, and still resolving, because D1 binds: the trace-debugger
		// skill alone holds 58 references to `ailang trace ...`, and
		// `observatory backfill` and `dashboard spans` are called from
		// tools/ and .claude/skills/.
		//
		// Their Run routes through `chains` (runFoldedLegacy) instead of
		// calling the command directly, so the alias and the canonical
		// spelling are the same code path rather than two that can drift.
		// The argv round trip is exact; commands_folded_test.go byte-diffs it.
		{
			Name:    "trace",
			Group:   groupOps,
			Hidden:  true,
			Summary: "Distributed trace management",
			Run:     runFoldedLegacy("trace"),
		},
		{
			Name:    "observatory",
			Group:   groupOps,
			Hidden:  true,
			Summary: "Observatory analytics",
			Run:     runFoldedLegacy("observatory"),
		},
		{
			Name:    "chains",
			Group:   groupOps,
			Summary: "Execution chains, traces, observatory and dashboard queries",
			Run:     noArgs(chainsCommand),
		},
		{
			Name:    "dashboard",
			Group:   groupOps,
			Hidden:  true,
			Summary: "Dashboard operations for task visualization",
			Run:     runFoldedLegacy("dashboard"),
		},
		{
			Name:    "budget",
			Group:   groupOps,
			Summary: "Budget monitoring",
			Run:     noArgs(budgetCommand),
		},
		{
			Name:    "models",
			Group:   groupOps,
			Summary: "Model registry: list, show, pricing",
			Run:     modelsCommand,
		},
		{
			Name:    "mission",
			Group:   groupOps,
			Summary: "Mission registry, iteration, role dispatch and reports",
			// mission maps error classes onto exit codes, so it reports and
			// exits inside its own closure instead of returning the error.
			Run: func(args []string) error {
				if err := missionCommand(args); err != nil {
					fmt.Fprintf(os.Stderr, "%s: %v\n", red("Error"), err)
					os.Exit(missionErrorExitCode(err))
				}
				return nil
			},
		},
		{
			Name:    "coordinator",
			Group:   groupOps,
			Summary: "Manage the autonomous agent daemon",
			Run:     coordinatorCommand,
		},
		{
			Name:    "storage",
			Group:   groupOps,
			Summary: "Storage plane status (which backend each store resolved to)",
			Run:     storageCommand,
		},
		{
			Name:    "workspaces",
			Group:   groupOps,
			Summary: "Workspace management",
			Run:     workspacesCommand,
		},
		{
			Name:    "exec",
			Group:   groupOps,
			Summary: "Unified AI execution for programmatic use",
			Run:     noArgs(runExec),
		},
		{
			Name:    "design-review",
			Group:   groupOps,
			Summary: "AI review of a design document",
			Run:     noArgs(runDesignReview),
		},
		{
			Name:    "design-quorum",
			Group:   groupOps,
			Summary: "N-reviewer design quorum, reject-by-default",
			Run:     noArgs(runDesignQuorum),
		},
		{
			Name:    "generate-extension-registry",
			Group:   groupDev,
			Summary: "Emit the static extension dispatch file from [extensions]",
			Run:     extRegistryGenCommand,
		},
		{
			Name:    "pkg",
			Summary: "Package registry inspection and coordination",
			Run:     pkgGroupCommand,
		},
		{
			Name:    "policy-check",
			Group:   groupDev,
			Summary: "Evaluate a policy program against its cases",
			Run:     noArgs(policyCheckCommand),
		},
		{
			Name:    "sandbox-check",
			Group:   groupDev,
			Summary: "Diagnose FS sandbox path resolution (AILANG_FS_SANDBOX)",
			Run: func(args []string) error {
				sandboxCheckCommand(args)
				return nil
			},
		},
	}
}

// runDaemonCommand is `ailang daemon`. It owns its own help because the same
// block serves two paths: `--help` (exit 0) and NO arguments (exit 1).
//
// Before S5 M1 a bare `ailang daemon` defaulted its subcommand to "run" and
// STARTED the daemon — the most dangerous default in the CLI, and the reason
// `daemon` is called out in the Phase 3 plan. It now prints this help and
// exits 1 without starting anything; `ailang daemon run` is unchanged.
func runDaemonCommand(args []string) error {
	if wantsHelp(args) {
		printDaemonHelp(os.Stdout)
		return nil
	}
	if len(args) == 0 {
		printDaemonHelp(os.Stdout)
		os.Exit(1)
	}
	daemonCommand()
	return nil
}

func printDaemonHelp(w io.Writer) {
	fmt.Fprintf(w, "%s - Local ailang daemon\n\n", bold("ailang daemon"))
	fmt.Fprintln(w, "Usage:")
	fmt.Fprintln(w, "  ailang daemon <subcommand>")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Subcommands:")
	fmt.Fprintf(w, "  %s        Run the daemon in the foreground\n", cyan("run"))
	fmt.Fprintf(w, "  %s    Install the daemon as a background service\n", cyan("install"))
	fmt.Fprintf(w, "  %s  Remove the installed service\n", cyan("uninstall"))
	fmt.Fprintf(w, "  %s     Show service status and recent log lines\n", cyan("status"))
	fmt.Fprintln(w)
	fmt.Fprintln(w, "A bare 'ailang daemon' no longer starts the daemon — name the subcommand.")
}
