package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sunholo-data/ailang/internal/ast"
	gen "github.com/sunholo-data/ailang/internal/gen/golang"
)

// sanitizePackageName converts a string to a valid Go package name
func sanitizePackageName(name string) string {
	// Replace invalid characters
	result := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			return r
		}
		if r >= 'A' && r <= 'Z' {
			return r + ('a' - 'A') // lowercase
		}
		if r == '_' || r == '-' {
			return '_'
		}
		return -1 // remove
	}, name)

	// Ensure doesn't start with number
	if len(result) > 0 && result[0] >= '0' && result[0] <= '9' {
		result = "pkg" + result
	}

	if result == "" {
		result = "generated"
	}

	return result
}

// sanitizeModuleName converts a module name to a valid Go identifier prefix.
// M-DX18: Used to namespace non-exported functions when compiling multiple modules
// to the same Go package. Unlike package names, module names preserve case since
// they're used as function name prefixes, not Go package names.
func sanitizeModuleName(name string) string {
	// Replace invalid characters with underscores
	result := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			return r
		}
		if r == '_' {
			return r
		}
		if r == '-' {
			return '_'
		}
		return -1 // remove
	}, name)

	// Ensure doesn't start with number
	if len(result) > 0 && result[0] >= '0' && result[0] <= '9' {
		result = "mod" + result
	}

	if result == "" {
		result = "module"
	}

	return result
}

func printCompileHelp() {
	fmt.Println(`Usage: ailang compile [options] <file.ail|directory> [...]

Compile AILANG source to Go. Supports files, directories, or both.

Options:
  --emit-go              Generate Go source code (required)
  --out <dir>            Output directory (default: "gen")
  --package-name <name>  Go package name (default: derived from first module)
  --release              Mark this as a release build (info only)
  --verify-contracts     Generate runtime contract checks (M-VERIFY Phase 0.5)
  --value-threshold <n>  Max fields for value-type records (default: 4, 0=all pointers)
  -h, --help             Show this help message

Examples:
  # Compile all .ail files in a directory
  ailang compile --emit-go sim/

  # Compile specific files
  ailang compile --emit-go world.ail npc_ai.ail

  # Mix directories and files
  ailang compile --emit-go sim/ extra.ail

  # Specify output directory and package name
  ailang compile --emit-go --out . --package-name sim_gen sim/

Output Structure:
  <out>/<package>/
  ├── types.go              # Generated ADT types (merged from all files)
  ├── debug_types_debug.go  # Debug effect (//go:build !release)
  ├── debug_types_release.go# Debug effect no-ops (//go:build release)
  ├── handlers.go           # Effect handler interfaces
  ├── runtime.go            # Shared runtime helpers
  ├── dictionaries.go       # Type class dictionaries (Num, Ord, Eq)
  ├── extern_stubs.go       # Stubs for extern functions (if any)
  ├── world.go              # Functions from world.ail
  ├── npc_ai.go             # Functions from npc_ai.ail
  └── step.go               # Functions from step.ail (one per source file)

Build Commands:
  Debug mode (default):  cd <out> && go build
  Release mode (no-op):  cd <out> && go build -tags release

The Debug effect uses Go build tags for zero-cost release builds.
In release mode, all Debug operations (Log, Assert) are no-ops.`)
}

// generateExternStubs generates Go stub code for extern functions
func generateExternStubs(pkgName string, funcs []*ast.FuncDecl) []byte {
	var buf strings.Builder

	buf.WriteString("// Code generated by ailang. DO NOT EDIT.\n")
	buf.WriteString("// Extern function stubs - implement these in your Go code.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	buf.WriteString("// TODO: Implement these extern functions.\n")
	buf.WriteString("// Copy the signatures below and add your implementation.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Type mapping (AILANG -> Go):\n")
	buf.WriteString("//   int    -> int64\n")
	buf.WriteString("//   float  -> float64\n")
	buf.WriteString("//   string -> string\n")
	buf.WriteString("//   bool   -> bool\n")
	buf.WriteString("//   [T]    -> []T (slice)\n")
	buf.WriteString("//   { field: T } -> *TypeName (pointer to generated struct)\n")
	buf.WriteString("//\n\n")

	for _, fn := range funcs {
		// Generate doc comment with AILANG signature
		buf.WriteString(fmt.Sprintf("// %s is an extern function declared in AILANG.\n", fn.Name))
		buf.WriteString("//\n")
		buf.WriteString("// AILANG signature:\n")
		buf.WriteString(fmt.Sprintf("//   extern func %s(", fn.Name))
		for i, param := range fn.Params {
			if param.Name == "_" && param.Type.String() == "()" {
				continue
			}
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(fmt.Sprintf("%s: %s", param.Name, param.Type.String()))
		}
		buf.WriteString(")")
		if fn.ReturnType != nil {
			buf.WriteString(fmt.Sprintf(" -> %s", fn.ReturnType.String()))
		}
		buf.WriteString("\n//\n")
		buf.WriteString("// Implement this function to provide the behavior.\n")
		buf.WriteString("// See docs/guides/go-interop.md for type mapping reference.\n")

		// Generate function signature
		buf.WriteString(fmt.Sprintf("func %s(", capitalize(fn.Name)))

		// Generate parameters
		for i, param := range fn.Params {
			if param.Name == "_" && param.Type.String() == "()" {
				// Skip unit parameters
				continue
			}
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(fmt.Sprintf("%s %s", param.Name, ailangTypeToGo(param.Type)))
		}
		buf.WriteString(")")

		// Generate return type
		if fn.ReturnType != nil {
			buf.WriteString(fmt.Sprintf(" %s", ailangTypeToGo(fn.ReturnType)))
		}

		buf.WriteString(" {\n")
		buf.WriteString("\tpanic(\"not implemented: ")
		buf.WriteString(fn.Name)
		buf.WriteString("\")\n")
		buf.WriteString("}\n\n")
	}

	return []byte(buf.String())
}

// capitalize makes the first letter uppercase (for exported Go functions)
func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// isUserDefinedGoType delegates to the canonical implementation in the codegen package.
// M-CODEGEN-SUSTAINABILITY: Single source of truth for user-defined type detection.
func isUserDefinedGoType(goType string) bool {
	return gen.IsUserDefinedType(goType)
}

// extractFieldTypes extracts Go type strings from AST constructor fields
func extractFieldTypes(fields []*ast.ConstructorField) []string {
	types := make([]string, len(fields))
	for i, field := range fields {
		types[i] = ailangTypeToGo(field.Type)
	}
	return types
}

// extractFieldNames extracts field names from AST constructor fields
// Returns empty strings for positional fields (no name specified)
func extractFieldNames(fields []*ast.ConstructorField) []string {
	names := make([]string, len(fields))
	for i, field := range fields {
		names[i] = field.Name // Empty string if positional
	}
	return names
}

// extractRecordTypeInfo extracts field information from a record type definition.
// M-DX13: Returns Go field names (PascalCase) and a map of field name -> Go type.
func extractRecordTypeInfo(rec *ast.RecordType) ([]string, map[string]string) {
	fields := make([]string, len(rec.Fields))
	fieldTypes := make(map[string]string, len(rec.Fields))
	for i, field := range rec.Fields {
		goFieldName := capitalize(field.Name)
		fields[i] = goFieldName
		fieldTypes[goFieldName] = ailangTypeToGo(field.Type)
	}
	return fields, fieldTypes
}

// expandFilenames expands directory arguments into .ail files.
// If an argument is a directory, all .ail files in it are included.
// Files are sorted alphabetically for deterministic compilation order.
func expandFilenames(args []string) []string {
	var result []string
	for _, arg := range args {
		info, err := os.Stat(arg)
		if err != nil {
			// Keep the argument as-is (will fail later with proper error)
			result = append(result, arg)
			continue
		}

		if info.IsDir() {
			// Expand directory recursively to all .ail files
			var ailFiles []string
			err := filepath.WalkDir(arg, func(path string, d os.DirEntry, err error) error {
				if err != nil {
					return nil // skip unreadable dirs
				}
				if !d.IsDir() && strings.HasSuffix(d.Name(), ".ail") {
					ailFiles = append(ailFiles, path)
				}
				return nil
			})
			if err != nil {
				fmt.Fprintf(os.Stderr, "%s: cannot walk directory '%s': %v\n", yellow("Warning"), arg, err)
				continue
			}

			result = append(result, ailFiles...)

			if len(ailFiles) > 0 {
				fmt.Printf("%s Found %d .ail files in %s/\n", cyan("→"), len(ailFiles), arg)
			} else {
				fmt.Fprintf(os.Stderr, "%s: no .ail files found in directory '%s'\n", yellow("Warning"), arg)
			}
		} else {
			// Regular file
			result = append(result, arg)
		}
	}
	return result
}

// ailangTypeToGo converts an AILANG type to a Go type string
func ailangTypeToGo(t ast.Type) string {
	switch typ := t.(type) {
	case *ast.SimpleType:
		switch typ.Name {
		case "int":
			return "int64"
		case "float":
			return "float64"
		case "string":
			return "string"
		case "bool":
			return "bool"
		case "()":
			return "struct{}"
		default:
			// M-CODEGEN-TYPE-ASSERTIONS: User-defined types are pointers in function signatures
			// This matches generateTypedRecord which generates &World{...} for record literals
			// Records/ADTs are always pointers when passed through interface{} boundaries
			return "*" + capitalize(typ.Name)
		}
	case *ast.ListType:
		elemType := ailangTypeToGo(typ.Element)
		// M-CODEGEN-POINTER-RETURN-TYPES: User-defined SimpleTypes now return *TypeName
		// So elemType is already "*CrewPosition" for user-defined types
		// Just concatenate "[]" + elemType - no additional "*" needed
		if strings.HasPrefix(elemType, "*") {
			// Already a pointer type (e.g., *CrewPosition) - just make it a slice
			return "[]" + elemType // []*CrewPosition
		}
		if isUserDefinedGoType(elemType) {
			// Fallback for non-pointer user types (shouldn't happen with current logic)
			return "[]*" + elemType
		}
		return "[]" + elemType
	case *ast.ArrayType:
		// M-TYPE1: Arrays use the same Go representation as lists (slices)
		elemType := ailangTypeToGo(typ.Element)
		// M-CODEGEN-POINTER-RETURN-TYPES: Same logic as ListType
		if strings.HasPrefix(elemType, "*") {
			return "[]" + elemType // []*TypeName
		}
		if isUserDefinedGoType(elemType) {
			return "[]*" + elemType
		}
		return "[]" + elemType
	case *ast.RecordType:
		return "map[string]interface{}"
	case *ast.TypeApp:
		// M-CODEGEN-LIST-TYPE: Handle list types normalized from [T] syntax
		// Parser creates TypeApp("list", [T]) for [T] syntax (DX-17 Phase 2)
		if typ.Constructor == "list" && len(typ.Args) > 0 {
			elemType := ailangTypeToGo(typ.Args[0])
			// Same logic as ast.ListType case
			if strings.HasPrefix(elemType, "*") {
				return "[]" + elemType // []*TypeName
			}
			if isUserDefinedGoType(elemType) {
				return "[]*" + elemType
			}
			return "[]" + elemType
		}
		// M-CODEGEN-OPTION-TYPE-ASSERT: Handle generic type applications like Option[Color]
		// ADTs (including Option) are always pointers in Go
		// The type argument is erased - Option[Color] and Option[int] both become *Option
		return "*" + capitalize(typ.Constructor)
	default:
		return "interface{}"
	}
}

// ailangTypeToGoWithValueRecords converts an AILANG type to a Go type string,
// checking if record types are value types.
// M-CODEGEN-VALUE-TYPES: Value records return TypeName instead of *TypeName.
func ailangTypeToGoWithValueRecords(t ast.Type, valueRecords map[string]bool) string {
	switch typ := t.(type) {
	case *ast.SimpleType:
		switch typ.Name {
		case "int":
			return "int64"
		case "float":
			return "float64"
		case "string":
			return "string"
		case "bool":
			return "bool"
		case "()":
			return "struct{}"
		default:
			// M-CODEGEN-VALUE-TYPES: Check if this is a value record
			goTypeName := capitalize(typ.Name)
			if valueRecords[goTypeName] {
				return goTypeName // Value type - no pointer
			}
			// Pointer type for other user-defined types
			return "*" + goTypeName
		}
	case *ast.ListType:
		elemType := ailangTypeToGoWithValueRecords(typ.Element, valueRecords)
		// M-CODEGEN-VALUE-TYPES: Value records already return TypeName (no *)
		// Pointer types return *TypeName
		if strings.HasPrefix(elemType, "*") {
			// Already a pointer type - just make it a slice []*Type
			return "[]" + elemType
		}
		// Check if this is a value type (no * prefix means it's a value record or primitive)
		if isUserDefinedGoType(elemType) {
			// Value record - return []Type
			return "[]" + elemType
		}
		return "[]" + elemType
	case *ast.ArrayType:
		// M-TYPE1: Arrays use the same Go representation as lists (slices)
		elemType := ailangTypeToGoWithValueRecords(typ.Element, valueRecords)
		if strings.HasPrefix(elemType, "*") {
			return "[]" + elemType
		}
		if isUserDefinedGoType(elemType) {
			return "[]" + elemType
		}
		return "[]" + elemType
	case *ast.RecordType:
		return "map[string]interface{}"
	case *ast.TypeApp:
		// M-CODEGEN-LIST-TYPE: Handle list types normalized from [T] syntax
		if typ.Constructor == "list" && len(typ.Args) > 0 {
			elemType := ailangTypeToGoWithValueRecords(typ.Args[0], valueRecords)
			if strings.HasPrefix(elemType, "*") {
				return "[]" + elemType
			}
			if isUserDefinedGoType(elemType) {
				return "[]" + elemType
			}
			return "[]" + elemType
		}
		// ADTs (including Option) are always pointers in Go
		return "*" + capitalize(typ.Constructor)
	default:
		return "interface{}"
	}
}
