// ailang generate-extension-registry
// Reads [extensions] from ailang.toml and emits a static-import AILANG dispatch file.
// See design_docs/planned/v0_17_0/m-ailang-ext-registry-gen.md

package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/sunholo-data/ailang/internal/pkg"
)

const extRegistryTemplate = `-- GENERATED by ailang generate-extension-registry
-- Source: ailang.toml [extensions]
-- Do not edit. Regenerate: ailang generate-extension-registry

module {{.ModuleName}}

{{range .Imports}}import {{.ImportPrefix}}{{.ModulePath}}/register (register_with_config as register_{{.Alias}})
{{end}}import {{.ConfigModule}} ({{.ConfigType}})
import {{.HooksModule}} ({{.HooksType}}){{if .RegistryModule}}
import {{.RegistryModule}} ({{.RegistryType}})
import std/string (split, trim){{end}}
import std/option (Option, Some, None)

{{if .RegistryModule}}func{{else}}export func{{end}} resolve(name: string, cfg: {{.ConfigType}}) -> Option[{{.HooksType}}] {
{{range $i, $pkg := .Packages}}  {{if $i}}else {{end}}if name == "{{$pkg.ShortName}}" then Some(register_{{$pkg.Alias}}(cfg))
{{end}}  else None
}
{{- if .RegistryModule}}

func with_id(h: {{.HooksType}}, id: string) -> {{.HooksType}} {
  { h | id: id }
}

func parse_tokens(xs: [string], idx: int, acc: [{{.HooksType}}], cfg: {{.ConfigType}}) -> {{.RegistryType}} ! {Env, FS} {
  match xs {
    [] => { hooks: acc },
    raw :: rest => {
      let name = trim(raw);
      match resolve(name, cfg) {
        None => parse_tokens(rest, idx + 1, acc, cfg),
        Some(hook) => {
          let id = "${name}#${show(idx)}";
          parse_tokens(rest, idx + 1, acc ++ [with_id(hook, id)], cfg)
        }
      }
    }
  }
}

export func parse_core_ext_order(raw: string, cfg: {{.ConfigType}}) -> {{.RegistryType}} ! {Env, FS} {
  if trim(raw) == "" then { hooks: [] }
  else parse_tokens(split(raw, ","), 0, [], cfg)
}
{{- end}}
`

type extImport struct {
	ModulePath   string // e.g. "motoko-ext-compaction" or "sunholo/motoko_ext_test_dummy"
	Alias        string // e.g. "compaction"
	ImportPrefix string // "pkg/" for vendor-prefixed packages, "" for legacy unvendored
}

type extPkg struct {
	ShortName string // e.g. "compaction"
	Alias     string // e.g. "compaction"
}

type extRegistryTemplateData struct {
	ModuleName     string
	Imports        []extImport
	ConfigModule   string
	ConfigType     string
	HooksModule    string
	HooksType      string
	RegistryModule string
	RegistryType   string
	Packages       []extPkg
}

// deriveShortName converts a package ref to a short identifier.
// "motoko-ext-exa-search@0.4.1" → "exa_search"       (unvendored, hyphenated)
// "sunholo/motoko_ext_exa_search@0.4.1" → "exa_search" (vendor-prefixed, underscored)
// "sunholo/motoko_ext_abi@1.0.0" → "abi"
// "my-tool" → "my_tool"
func deriveShortName(pkgRef string) string {
	name := stripVersion(pkgRef)
	// Strip vendor prefix (vendor/name → name) for packages using vendor/name format.
	if i := strings.IndexByte(name, '/'); i >= 0 {
		name = name[i+1:]
	}
	// Strip motoko-ext- prefix (hyphenated) or motoko_ext_ prefix (underscored).
	name = strings.TrimPrefix(name, "motoko-ext-")
	name = strings.TrimPrefix(name, "motoko_ext_")
	return strings.ReplaceAll(name, "-", "_")
}

// stripVersion returns the name part before '@'.
func stripVersion(pkgRef string) string {
	if i := strings.IndexByte(pkgRef, '@'); i >= 0 {
		return pkgRef[:i]
	}
	return pkgRef
}

// splitImportPath splits "module/path.TypeName" into module path and type name.
func splitImportPath(importRef string) (module, typeName string, err error) {
	dot := strings.LastIndexByte(importRef, '.')
	if dot < 0 {
		return "", "", fmt.Errorf("import ref %q must be in module/path.TypeName format", importRef)
	}
	return importRef[:dot], importRef[dot+1:], nil
}

func extRegistryGenCommand(args []string) error {
	fs := flag.NewFlagSet("generate-extension-registry", flag.ContinueOnError)
	configFile := fs.String("config", "ailang.toml", "Path to ailang.toml")
	outputFile := fs.String("output", "", "Override output file path (default: from ailang.toml or registry_generated.ail)")
	dryRun := fs.Bool("dry-run", false, "Print generated file to stdout instead of writing")
	if err := fs.Parse(args); err != nil {
		if err == flag.ErrHelp {
			return nil
		}
		return err
	}

	m, err := pkg.LoadManifestFile(*configFile)
	if err != nil {
		return fmt.Errorf("load manifest: %w", err)
	}

	ext := m.Extensions
	if len(ext.Packages) == 0 {
		fmt.Fprintln(os.Stderr, "ailang generate-extension-registry: no [extensions].packages in ailang.toml — nothing to generate")
		return nil
	}

	// Resolve lock file from same directory as ailang.toml
	manifestDir := filepath.Dir(*configFile)
	lf, err := pkg.LoadLockFile(manifestDir)
	if err != nil {
		return fmt.Errorf("load lockfile: %w", err)
	}

	// Determine output path (write location)
	outPath := ext.Output
	if *outputFile != "" {
		outPath = *outputFile
	}
	if outPath == "" {
		outPath = "registry_generated.ail"
	}

	// Determine module name: always derive from the TOML output field (relative path),
	// not the resolved write location — the -output flag just overrides where the file
	// is written, not the module identity in the generated AILANG source.
	moduleName := ext.ModuleName
	if moduleName == "" {
		moduleRef := ext.Output
		if moduleRef == "" {
			moduleRef = "registry_generated.ail"
		}
		moduleName = strings.TrimSuffix(moduleRef, ".ail")
	}

	// Verify all packages are locked and build template data
	configModule, configType, err := splitImportPath(ext.ConfigImport)
	if err != nil {
		return fmt.Errorf("config_import: %w", err)
	}
	hooksModule, hooksType, err := splitImportPath(ext.HooksImport)
	if err != nil {
		return fmt.Errorf("hooks_import: %w", err)
	}
	var registryModule, registryType string
	if ext.RegistryImport != "" {
		registryModule, registryType, err = splitImportPath(ext.RegistryImport)
		if err != nil {
			return fmt.Errorf("registry_import: %w", err)
		}
	}

	var imports []extImport
	var packages []extPkg
	for _, pkgRef := range ext.Packages {
		name := stripVersion(pkgRef)
		if _, ok := lf.FindPackage(name); !ok {
			return fmt.Errorf("package %q is listed in [extensions] but not found in ailang.lock — run: ailang lock", name)
		}
		alias := deriveShortName(pkgRef)
		// Vendor-prefixed packages (vendor/name format) are external packages and
		// require the "pkg/" import prefix. Unvendored names are treated as local.
		prefix := ""
		if strings.Contains(name, "/") {
			prefix = "pkg/"
		}
		imports = append(imports, extImport{ModulePath: name, Alias: alias, ImportPrefix: prefix})
		packages = append(packages, extPkg{ShortName: alias, Alias: alias})
	}

	data := extRegistryTemplateData{
		ModuleName:     moduleName,
		Imports:        imports,
		ConfigModule:   configModule,
		ConfigType:     configType,
		HooksModule:    hooksModule,
		HooksType:      hooksType,
		RegistryModule: registryModule,
		RegistryType:   registryType,
		Packages:       packages,
	}

	tmpl, err := template.New("registry").Parse(extRegistryTemplate)
	if err != nil {
		return fmt.Errorf("template parse: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("template execute: %w", err)
	}

	if *dryRun {
		fmt.Print(buf.String())
		return nil
	}

	// Atomic write: write to .tmp then rename
	tmpPath := outPath + ".tmp"
	if err := os.WriteFile(tmpPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write temp file: %w", err)
	}
	if err := os.Rename(tmpPath, outPath); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("rename to %s: %w", outPath, err)
	}

	fmt.Fprintf(os.Stderr, "generated %s (%d packages)\n", outPath, len(packages))
	return nil
}
