#!/usr/bin/env bash
# check_claude_mods_drift.sh — the pi ports under tools/claude-mods/ carry a
# verbatim copy of their pi extension's pure functions in hooks/core.ts (neither
# channel can import a shared file: pi extensions are copied flat into
# cmd/ailang/pi_assets/, and a plugin cannot import outside its folder).
#
# A core.ts names its source and the declarations it copies on its first line:
#   // pi-core: .pi/extensions/prepush-gate.ts goRoots makeTargetDefined ...
#
#   scripts/check_claude_mods_drift.sh          # fail when any copy differs
#   scripts/check_claude_mods_drift.sh --write  # regenerate every core.ts
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:-check}"

python3 - "$ROOT" "$MODE" <<'PY'
import pathlib, re, sys

root, mode = pathlib.Path(sys.argv[1]), sys.argv[2]
HEADER = re.compile(r"^// pi-core: (\S+) (.+)$")

def declaration(src: str, name: str) -> str:
    """One exported function/interface/type, with the JSDoc block right above it."""
    m = re.search(rf"^export (?:async )?(?:function|interface|type) {re.escape(name)}\b", src, re.M)
    if not m:
        raise SystemExit(f"drift: {name} not found in pi source")
    start = m.start()
    prefix = src[:start]
    if prefix.endswith("*/\n"):
        # The JSDoc block must open at the start of a line ("cmd/**/*.go" in a
        # string is not one) and hold no other close before its own.
        opened = prefix.rfind("\n/**") + 1
        if opened > 0 and "*/" not in prefix[opened:-3]:
            start = opened
    end = src.find("\n}\n", m.start())
    if end < 0 or (src.find(";\n", m.start()) < end and " type " in src[m.start():m.end()]):
        end = src.find(";\n", m.start()) - 1
    return src[start:end + 3].rstrip() + "\n"

def render(source: str, names: list[str]) -> str:
    src = (root / source).read_text()
    parts = [declaration(src, n) for n in names]
    return (
        f"// pi-core: {source} {' '.join(names)}\n"
        "// Generated by scripts/check_claude_mods_drift.sh --write from the pi source\n"
        "// above. Do not edit here: change pi, then regenerate.\n\n"
        + "\n".join(parts)
    )

failed = False
for core in sorted(root.glob("tools/claude-mods/*/hooks/core.ts")):
    first = core.read_text().split("\n", 1)[0]
    m = HEADER.match(first)
    if not m:
        print(f"drift: {core.relative_to(root)} has no '// pi-core:' header"); failed = True; continue
    want = render(m.group(1), m.group(2).split())
    if mode == "--write":
        core.write_text(want); print(f"wrote {core.relative_to(root)}")
    elif core.read_text() != want:
        print(f"drift: {core.relative_to(root)} differs from {m.group(1)} (run with --write after checking pi)")
        failed = True
    else:
        print(f"ok    {core.relative_to(root)}")
sys.exit(1 if failed else 0)
PY
