#!/bin/bash
# Integration test for M-COORD-GITHUB-AUTO-ROUTING
# Tests GitHub issue creation, label management, and comment posting

set -e

REPO="sunholo-data/ailang"
TEST_LABEL="coordinator:test"
ISSUE_TITLE="[TEST] GitHub Integration Test $(date +%Y%m%d_%H%M%S)"
ISSUE_BODY="This is an automated test issue for the coordinator GitHub integration.

**Type:** test
**Priority:** low

This issue should be:
1. Imported to coordinator inbox
2. Have a 'working' comment posted
3. Be watchable for approval labels

---
*Auto-generated by test_github_integration.sh*"

echo "═══════════════════════════════════════════════════════════════"
echo " GitHub Integration Test - M-COORD-GITHUB-AUTO-ROUTING"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Check gh is authenticated
echo "1/6 Checking GitHub authentication..."
if ! gh auth status &>/dev/null; then
    echo "  ❌ Not authenticated. Run: gh auth login"
    exit 1
fi
CURRENT_USER=$(gh api user -q '.login')
echo "  ✓ Authenticated as: $CURRENT_USER"
echo ""

# Create test issue
echo "2/6 Creating test issue..."
ISSUE_URL=$(gh issue create \
    --repo "$REPO" \
    --title "$ISSUE_TITLE" \
    --body "$ISSUE_BODY" \
    --label "$TEST_LABEL" \
    2>&1)
ISSUE_NUM=$(echo "$ISSUE_URL" | grep -oE '[0-9]+$')
echo "  ✓ Created issue #$ISSUE_NUM"
echo "  URL: $ISSUE_URL"
echo ""

# Test label operations
echo "3/6 Testing label operations..."

# Add a label
echo "  Adding 'needs-design-approval' label..."
gh issue edit "$ISSUE_NUM" --repo "$REPO" --add-label "needs-design-approval" 2>/dev/null || \
    gh api "repos/$REPO/issues/$ISSUE_NUM/labels" -f "labels[]=needs-design-approval" &>/dev/null || true
echo "  ✓ Label added"

# List labels
echo "  Current labels:"
gh issue view "$ISSUE_NUM" --repo "$REPO" --json labels -q '.labels[].name' | while read label; do
    echo "    - $label"
done
echo ""

# Test comment posting
echo "4/6 Testing comment posting..."
COMMENT_BODY="## 🔄 Coordinator Test Comment

This is a test comment from the integration test script.

| Field | Value |
|-------|-------|
| Test ID | $(date +%s) |
| Status | Testing |

---
*Posted by test_github_integration.sh*"

gh issue comment "$ISSUE_NUM" --repo "$REPO" --body "$COMMENT_BODY"
echo "  ✓ Comment posted"
echo ""

# Test importing to coordinator
echo "5/6 Testing message import..."
echo "  Running: ailang messages import-github --labels $TEST_LABEL"
./bin/ailang messages import-github --labels "$TEST_LABEL" 2>&1 | head -10
echo "  ✓ Import completed"
echo ""

# Check message was imported
echo "6/6 Verifying message import..."
echo "  Checking for imported message..."
IMPORTED=$(./bin/ailang messages list --json 2>/dev/null | jq -r ".[] | select(.title | contains(\"$ISSUE_NUM\")) | .id" | head -1)
if [ -n "$IMPORTED" ]; then
    echo "  ✓ Message imported: $IMPORTED"
else
    echo "  ⚠ Message not found (may already exist or filtering mismatch)"
fi
echo ""

# Cleanup option
echo "═══════════════════════════════════════════════════════════════"
echo " Test Complete!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Test issue: $ISSUE_URL"
echo ""
echo "To clean up:"
echo "  gh issue close $ISSUE_NUM --repo $REPO --comment 'Test completed'"
echo ""
echo "To test approval workflow manually:"
echo "  1. Start coordinator: ailang coordinator start"
echo "  2. Add 'design-approved' label to issue #$ISSUE_NUM"
echo "  3. Watch coordinator logs: tail -f ~/.ailang/logs/coordinator.log"
echo ""

# Ask to close
read -p "Close test issue now? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    gh issue close "$ISSUE_NUM" --repo "$REPO" --comment "Test completed - closing automatically"
    echo "  ✓ Issue closed"
fi
