// Package config is the one place AILANG reads its environment: the cloud
// identity a process acts on, the storage plane, the loader of
// ~/.ailang/config.yaml, the deprecated production defaults being retired,
// and — since M-V1-SIMPLIFY-S4 M2 — every other operator-facing variable,
// through a typed getter grouped by area (compiler.go, paths.go, trace.go,
// telemetry.go, coordinator.go, job.go, server.go, executor.go, providers.go,
// mission.go, rig.go, pubsub.go, pkgregistry.go, models.go, mcp.go,
// microrag.go, apiserver.go, notify.go).
//
// # Precedence
//
// Written once, here, and true of every getter: a command-line flag beats the
// environment, the environment beats the config file, and the config file
// beats the default. A getter returns what the ENVIRONMENT says (or the
// default); the caller that owns a flag applies it above the getter, and the
// caller that owns a config-file section reads it through Load below the
// getter. Where a getter documents a fallback chain of its own (CloudProject,
// RegistryValidatorURL, TraceProjectFromEnv) that chain is the order between
// several environment sources, not an exception to this rule.
//
// # Registry and the generated reference
//
// Every variable is one Var in Registry (registry.go): its name — always an
// Env* constant, which is what the getter reads — its default, its area and
// one line of documentation. A getter with a default reads it from the
// Registry (getOr), so docs/docs/reference/env-vars.md, generated by
// `make docs-env` (tools/gen-env-docs), cannot drift from the code.
// registry_test.go fails when an Env* constant is missing from the Registry,
// when an entry has no constant, or when a name is read as a string literal.
//
// Getters are reads and only reads. A getter returns exactly what os.Getenv
// returned at the site it replaced, with the same default and the same
// trimming, and nothing here changes which process sees what: the rig's
// `launchctl setenv` domain globals reach a launchd job exactly as before
// (docs/docs/guides/debugging.md, "Ollama Streaming Timeouts"). Variables a
// parent SETS for a child (os.Setenv, cmd.Env) are not reads and are not
// routed here. Names chosen at runtime — a `--api-key-env` flag, the
// credential variable an AI provider declares for itself — go through Raw.
// The DEBUG_* compiler knobs stay where they are by rule.
//
// # Storage plane (M-V1-SIMPLIFY-S3 M3)
//
// StoragePlane resolves AILANG_STORAGE=local|gcp|hybrid and the per-store
// overrides AILANG_STORAGE_{MESSAGING,COORDINATOR,OBSERVATORY}=local|gcp into
// one Storage value naming each store's mode AND its source. It is the only
// reader of those variables; internal/storage opens what it says and `ailang
// storage status` prints it per store. The retired selectors
// AILANG_MESSAGES_STORE, AILANG_COORDINATOR_REMOTE, AILANG_CHAINS_READ and
// AILANG_CHAINS_CLOUD are hard errors naming the replacement for one release.
// CoordinatorMode reads COORDINATOR_MODE and refuses cloud on a plane whose
// coordinator or messaging store is not in Firestore.
//
// # Config file
//
// Load parses the file named by AILANG_CONFIG, else ~/.ailang/config.yaml,
// once per process per path (re-read when it changes on disk), and hands
// sections to callers through File.Section. Nothing else opens the file.
//
// # Cloud project
//
// CloudProject resolves, in order, and stops at the first non-empty answer:
//
//  1. AILANG_CLOUD_PROJECT
//  2. GOOGLE_CLOUD_PROJECT (what Cloud Run, GKE and App Engine set)
//  3. the pubsub.project_id key of ~/.ailang/config.yaml (or the file named by
//     AILANG_CONFIG), read through Load.
//  4. the GCE metadata server, with a short timeout, unless AILANG_NO_METADATA
//     is set. The outcome is cached for the life of the process, so a laptop
//     pays the timeout once, not per call.
//
// When nothing resolves it returns ErrNoCloudProject. There is no default:
// acting on a guessed project looks exactly like success, and the gcloud CLI's
// current project is deliberately not consulted because it points at whatever
// the operator last worked on. GCP_PROJECT, an older alias some sites read,
// is no longer honoured.
//
// # Region
//
// Region resolves AILANG_CLOUD_REGION, then GOOGLE_CLOUD_REGION, then falls
// through to DeprecatedDefault with the value the fleet was hard-coded to.
//
// # Deprecated defaults (ruling D3, 2026-09-15)
//
// Production defaults such as "ailang-multivac" and "europe-west1" become a
// deprecation warning now and a hard error in v1.0.0. DeprecatedDefault is the
// only sanctioned way to keep using one: it returns the value and writes ONE
// warning per process per variable to stderr, naming what to set. With
// AILANG_STRICT_CONFIG=1 it refuses instead and returns an error wrapping
// ErrDeprecatedDefault — the v1.0.0 behaviour, testable today.
//
// # The rule
//
// This package is the ONLY place that reads the environment, apart from
// internal/statedir (a stdlib-only leaf below this one; its AILANG_STATE_DIR
// is registered here for the reference), internal/testutil (test-lane
// opt-ins) and the DEBUG_* knobs. Every other package calls in. tools/simplicity_metrics.sh counts the leaks as
// getenv_outside_config, and a forbidigo rule on os.Getenv/os.LookupEnv
// enforces it in lint.
//
// It is a leaf — standard library plus gopkg.in/yaml.v3 — so the store
// implementations, the AI providers and cmd/ailang can all import it.
// leaf_test.go enforces that.
package config
