title: AILANG Documentation  
description: AI-first programming language
baseurl: "/ailang"
url: "https://sunholo-data.github.io"

theme: minima

# Show all important pages in header
header_pages:
  - index.md
  - guides/getting-started.md
  - guides/development.md  
  - reference/language-syntax.md
  - reference/implementation-status.md
  - reference/repl-commands.md
  - prompts/index.md

markdown: kramdown
highlighter: rouge

# Better minima skin
minima:
  skin: dark
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
